### ISSUE TITLE
Type annotations to improve performance

### ISSUE THREAD

**Issue by datnamer** [pybee/voc#202] opened 2016-07-22 16:04 UTC
Can type annotations be optionally used to improve performance if enforced at runtime, or the program is strictly analyzed at compile time?

Either for this or any of the other projects.

**Comment by MarkusH** [comment] 2016-07-22 18:46
This is possibly a duplicate of #75

**Comment by freakboy3742** [comment] 2016-07-23 18:02
As @MarkusH notes, this is a duplicate of #75; but yes, optimisation of this kind is a distinct possibility. However, getting the base language working first is the priority.

**Closed by freakboy3742** 2016-07-23 18:02 UTC
Labels: duplicate
