### ISSUE TITLE
Implement the CALL_FUNCTION_KW opcode

### ISSUE THREAD

**Issue by aftalavera** [pybee/voc#214] opened 2016-07-29 15:32 UTC
I keep getting this error: AttributeError: module 'voc.python.opcodes' has no attribute 'CALL_FUNCTION_KW'.

**Comment by freakboy3742** [comment] 2016-07-30 16:18
@aftalavera CALL_FUNCTION_KW is one of the Python opcodes; the error has been raised because support for that opcode hasn't been implemented yet. 

Changing the ticket title to reference the cause of the problem.

**Comment by aftalavera** [comment] 2016-07-30 16:49
Thanks for the answer how can I help?

**Comment by freakboy3742** [comment] 2016-07-30 17:38
@aftalavera The best contribution you could make at the moment is to formalise the test case that causes this failure. [`tests/structures/test_function.py`](https://github.com/pybee/voc/blob/master/tests/structures/test_function.py) contains a bunch of examples for function invocation, but clearly the case that causes the `CALL_FUNCTION_KW` opcode to be used isn't being invoked. If you can create a test case that raises an error, and mark the test case as an `@expectedFailure`, it will make it much easier to establish when we've got things working. 

There's also the `CALL_FUNCTION_VAR_KW` opcode, which is also unimplemented; if you can provide an example for this as well, that would be fantastic.

**Comment by aftalavera** [comment] 2016-08-02 06:51
I noticed a third case CALL_FUNCTION_VAR. Need an example as well?

**Comment by freakboy3742** [comment] 2016-09-08 01:47
This should now be fixed by moving to an AST-based compilation approach.

**Closed by freakboy3742** 2016-09-08 01:47 UTC
